Added all the required features according to the JIRA doc
SciGaP/searchingsra-gateway-theme pull request #1
Opened 2018-03-06 20:03 UTC by stephenpaul2727

AIRAVATA - 2706
JIRA Link : https://issues.apache.org/jira/browse/AIRAVATA-2706

New improvements made according to the SearchingSRA-Theme-Change.pdf file in the linked JIRA Issue.

2018-03-06 22:17 UTC, machristie requested changes
Hi Stephen, this looks good. One request, can you replace all occurrences of `oii` with `searching-sra`?

2018-03-07 20:10 UTC, stephenpaul2727 commented
Added the requested changes and submitted compatibility PR to https://github.com/apache/airavata-php-gateway/pull/82

2018-03-09 20:24 UTC, machristie commented
👍

2018-03-09 20:24 UTC, machristie approved these changes

2018-03-09 20:24 UTC, merged